//=============================================================================
//
// Code generated by [VAPS XT 4.0.1]
//
//=============================================================================

#ifndef VXTCLSPOLYGONPOINTSCALCPLUGIN_H
#define VXTCLSPOLYGONPOINTSCALCPLUGIN_H

//=============================================================================
//                        I N C L U D E   F I L E S
//=============================================================================

#include "sqxQPlugin.h"

#include "vxtClsPolygonPointsCalc.h"

extern "C" VXTCLSPOLYGONPOINTSCALC_SPEC sqxQPlugin * sqxQPluginLoad(void); 

extern "C" VXTCLSPOLYGONPOINTSCALC_SPEC const vxtChar * sqxQPluginProductAPIVersion(void); 


//=============================================================================
//                                C L A S S
//=============================================================================

class VXTCLSPOLYGONPOINTSCALC_SPEC vxtClsPolygonPointsCalcPlugin : public sqxQPlugin
{
public:

   vxtClsPolygonPointsCalcPlugin(const vxtChar *, vxtFloat);

   virtual ~vxtClsPolygonPointsCalcPlugin();

   virtual vxtBool Initialize(void*);

   virtual void vCleanUp(void*);

   static vxtRTObject* s_pCreateRTObject(const void* a_pInitData);

   static void s_vDeleteRTObject(vxtRTObject* a_pObject);

private:

   // Disallow copy
   vxtClsPolygonPointsCalcPlugin( const vxtClsPolygonPointsCalcPlugin& );
   vxtClsPolygonPointsCalcPlugin& operator=( const vxtClsPolygonPointsCalcPlugin& );
};


#endif // VXTCLSPOLYGONPOINTSCALCPLUGIN_H

// END OF FILE

